version: "3"

services:
  db:
    image: postgres:12
    volumes:
      - ./db:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-data:/mongo-data/db
    ports:
      - '27018:27017'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/weather-forecast/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
